### ISSUE TITLE
Public Directory Deleted

### ISSUE THREAD

**Issue by VillainsRule** [Abyss-Services/Deployable#5]
In commit e48ab056fd40adebe21676039c0323ed5772abf5, the public directory was deleted.

**Comment by paxtonwarin** [comment]
Hey, Abyss Development team here.

The public directory is not needed, as we have a setup script in the directory. Because we use a special service, you must use this script in order to download and install everything.

Please follow the directions for either Windows or Ubuntu.

**Comment by paxtonwarin** [comment]
If you need further support, you can join our discord and ask around.

https://discord.gg/goabyss.
